ui: mocha-bdd
browsers:
  - name: chrome
    version: 26
  - name: firefox
    version: 4
  - name: internet explorer
    version: 9
  - name: iphone
    version: 8.1
  - name: microsoftedge
    version: 13
  - name: safari
    version: 6
browserify:
  - plugin: proxyquire-universal
  - plugin:
      - browserify-wrap
      - prefix: |
          window.open = function () {};
          (function () {
          var location = 'http://foo.share/';
          var screen = {width: 1920, height: 1080};
        suffix: |
          })();
